language: python
notifications:
  email: false
sudo: false
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - pypy3
install:
  - pip install -r tests/requirements.txt
  - python setup.py install
script:
  - nosetests --rednose --with-cov --cov-config=.coveragerc
after_success:
  # remove coverage files used for tests
  #   this command is not needed in your setup
  #   only this project
  - rm -rf tests/coverages
  # now send just codecov-python coverage stats out
  - codecov
