language: python
notifications:
  email: false
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - python setup.py install
  - nosetests
after_success:
  codecov
